// <auto-generated />
using System;
using EleFi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EleFi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EleFiDbContext))]
    partial class EleFiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("EleFi.Domain.Alerts.CaptureSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ContainerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorroboratingFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CounterpartyText")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Evidence")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OccurredAtTime")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("OccurredOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParseRuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentAppName")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorroboratingFingerprint");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.ToTable("CaptureSuggestions", (string)null);
                });

            modelBuilder.Entity("EleFi.Domain.Alerts.ParseRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppName")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyPattern")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Channel")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenderPattern")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ParseRules", (string)null);
                });

            modelBuilder.Entity("EleFi.Domain.Apps.App", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Colour")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DefaultContainerId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastUsedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Apps", (string)null);
                });

            modelBuilder.Entity("EleFi.Domain.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaptureSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("Changes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("EleFi.Domain.Containers.Container", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountNumberLast4")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Colour")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CreditLimitMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ifsc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("InstallmentMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstitutionName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InterestRateBps")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaturityDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningBalanceAsOf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OpeningBalanceMinor")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaymentDueDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatementDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TenureMonths")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumberLast4");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("DeletedAt IS NULL");

                    b.ToTable("Containers", (string)null);
                });

            modelBuilder.Entity("EleFi.Domain.Labels.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Colour")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("DeletedAt IS NULL");

                    b.ToTable("Labels", (string)null);
                });

            modelBuilder.Entity("EleFi.Domain.Parties.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContainerId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastUsedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.HasIndex("Name");

                    b.ToTable("Parties", (string)null);
                });

            modelBuilder.Entity("EleFi.Domain.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CaptureSource")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("DestinationAmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DestinationPartyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MarketplaceAppId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeedsReview")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OccurredAtTime")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("OccurredOn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PaymentAppId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceAmountMinor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourcePartyId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DestinationPartyId");

                    b.HasIndex("MarketplaceAppId");

                    b.HasIndex("OccurredOn");

                    b.HasIndex("PaymentAppId");

                    b.HasIndex("SourcePartyId");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_DistinctParties", "SourcePartyId <> DestinationPartyId");

                            t.HasCheckConstraint("CK_Transactions_PositiveAmounts", "SourceAmountMinor > 0 AND DestinationAmountMinor > 0");

                            t.HasCheckConstraint("CK_Transactions_SameCurrencySameAmount", "SourceCurrencyCode <> DestinationCurrencyCode OR SourceAmountMinor = DestinationAmountMinor");
                        });
                });

            modelBuilder.Entity("EleFi.Domain.Transactions.TransactionLabel", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId", "LabelId");

                    b.HasIndex("LabelId");

                    b.ToTable("TransactionLabels", (string)null);
                });

            modelBuilder.Entity("EleFi.Domain.Transactions.Transaction", b =>
                {
                    b.HasOne("EleFi.Domain.Parties.Party", "DestinationParty")
                        .WithMany()
                        .HasForeignKey("DestinationPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EleFi.Domain.Apps.App", "MarketplaceApp")
                        .WithMany()
                        .HasForeignKey("MarketplaceAppId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EleFi.Domain.Apps.App", "PaymentApp")
                        .WithMany()
                        .HasForeignKey("PaymentAppId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EleFi.Domain.Parties.Party", "SourceParty")
                        .WithMany()
                        .HasForeignKey("SourcePartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationParty");

                    b.Navigation("MarketplaceApp");

                    b.Navigation("PaymentApp");

                    b.Navigation("SourceParty");
                });

            modelBuilder.Entity("EleFi.Domain.Transactions.TransactionLabel", b =>
                {
                    b.HasOne("EleFi.Domain.Labels.Label", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EleFi.Domain.Transactions.Transaction", null)
                        .WithMany("Labels")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Label");
                });

            modelBuilder.Entity("EleFi.Domain.Transactions.Transaction", b =>
                {
                    b.Navigation("Labels");
                });
#pragma warning restore 612, 618
        }
    }
}
